repos:
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3.10
        stages: [ commit ]
        args: [ '-v',  '-S', '--line-length', '120' ]
  - repo: https://github.com/Botpy/pre-commit-pylint
    rev: v0.0.3
    hooks:
      - id: pylint-py3k
      - id: pylint-score-limit
        args:
        - --limit=9.5
        - --rcfile=./.pylintrc
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v8.0.0
    hooks:
      - id: commitlint
        stages: [ commit-msg ]
        additional_dependencies: [ '@commitlint/config-angular' ]
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        stages: [commit]
        types: [python]
        entry: pytest test
        language: system
        pass_filenames: false
        always_run: true
  - repo: local
    hooks:
      - id: mypy
        name: mypy-check
        stages: [commit]
        types: [python]
        entry: mypy .
        language: system
        pass_filenames: false
        always_run: true
